version: '3'

services:
  fastbot-sim:
    image: fastbot-sim
    build:
      context: .
      dockerfile: Dockerfile.gazebo
    container_name: fastbot-sim
    # network_mode: host
    # privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash"


  fastbot-slam:
    image: fastbot-slam
    build:
      context: .
      dockerfile: Dockerfile.slam
    container_name: fastbot-slam
    # network_mode: host
    # privileged: true
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash"


  fastbot-webapp:
    image: fastbot-webapp
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: fastbot-webapp
    hostname: fastbot-webapp
    restart: always
    ports:
      - "7000:80"

    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash"
