version: "3"


# --- 
# mkdir -p /root/.gazebo/models/fastbot_description
# cp -r /ros2_ws/src/fastbot_description/onshape /root/.gazebo/models/fastbot_description/
# --- 

services:
  fastbot-sim:
    image: fastbot-sim
    build:
      context: ../../             
      dockerfile: fastbot_ros2_docker/simulation/Dockerfile.gazebo
    container_name: fastbot-sim

    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_gazebo one_fastbot_room.launch.py"

  fastbot-slam:
    image: fastbot-slam
    build:
      context: ../../
      dockerfile: fastbot_ros2_docker/simulation/Dockerfile.slam
    container_name: fastbot-slam

    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    
    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_slam cartographer.launch.py"


  fastbot-webapp:
    image: fastbot-webapp
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: fastbot-webapp
    hostname: fastbot-webapp
    restart: always
    ports:
      - "7000:80"     # Webpage
      - "9090:9090"   # WebSocket (rosbridge)
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    command: bash -c "source /opt/ros/humble/setup.bash && /entrypoint.sh"

