version: "3"


# --- 
# mkdir -p /root/.gazebo/models/fastbot_description
# cp -r /ros2_ws/src/fastbot_description/onshape /root/.gazebo/models/fastbot_description/
# --- 

services:
  fastbot-sim:
    image: grboguz/oguzhangurbuz-cp22:fastbot-sim
    container_name: fastbot-sim
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_gazebo one_fastbot_room.launch.py"

  fastbot-slam:
    image: grboguz/oguzhangurbuz-cp22:fastbot-slam
    container_name: fastbot-slam
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_slam cartographer.launch.py"

  fastbot-webapp:
    image: grboguz/oguzhangurbuz-cp22:fastbot-webapp
    container_name: fastbot-webapp
    hostname: fastbot-webapp
    restart: always
    ports:
      - "7000:80"
      - "9090:9090"
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    command: bash -c "source /opt/ros/humble/setup.bash && /entrypoint.sh"

